services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    volumes:
      - pgdata:/home/master/code/docker_data/postgres
volumes:
  pgdata: