services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      cardump:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      cardump:
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  rabbitmq:
    image: rabbitmq:3.13.2-management-alpine
    networks:
      cardump:
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  auction-svc:
    image: neuromagusdocker/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User id=postgres;Password=pass;Database=auctions
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    networks:
      cardump:
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  search-svc:
    image: neuromagusdocker/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:pass@mongo
      - AuctionServiceUrl=http://auction-svc
    networks:
      cardump:
    ports:
      - 7002:80
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  identity-svc:
    image: neuromagusdocker/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=http://cardump.techdev.pro
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User id=postgres;Password=pass;Database=identity
      - VIRTUAL_HOST=id.techdev.pro
    networks:
      cardump:
        ipv4_address: 10.10.0.100
    depends_on:
      postgres:
        condition: service_healthy
    
  gateway-svc:
    image: neuromagusdocker/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=https://cardump.techdev.pro
      - VIRTUAL_HOST=api.techdev.pro
    networks:
      cardump:

  bid-svc:
    image: neuromagusdocker/bid-svc:latest
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:pass@mongo
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuction=http://auction-svc:7777
    networks:
      cardump:
    ports:
      - 7003:80
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notify-svc:
    image: neuromagusdocker/notify-svc:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
    networks:
      cardump:
    ports:
      - 7004:80
    depends_on:
      rabbitmq:
        condition: service_healthy

  web-app:
    image: neuromagusdocker/web-app:latest
    build: 
      context: .
      dockerfile: frontend/web-app/Dockerfile
    volumes:
      - /var/lib/web/data
    networks:
      cardump:
    extra_hosts:
      - id.techdev.pro:10.10.0.100
    environment:
      - NEXTAUTH_SECRET=somethingreallysecret
      - NEXTAUTH_URL=http://cardump.techdev.pro
      - NEXT_PUBLIC_NOTIFY_URL=http://gateway-svc/notifications
      - API_URL=http://gateway-svc/
      - ID_URL=http://id.techdev.pro
      - VIRTUAL_HOST=cardump.techdev.pro
      - VIRTUAL_PORT=3000
      
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    networks:
      cardump:
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt/archive/techdev.pro:/etc/nginx/certs:ro

networks:
  cardump:
    ipam:
      config:
        - subnet: 10.10.0.0/24
